with open('scripts/test-medical-routing.js', 'w', encoding='utf-8') as f:
    f.write('async function runTest() {\n')
    f.write('  const token = "test-device-token-123";\n')
    f.write('  const headers = { "Content-Type": "application/json", "X-Device-Token": token };\n')
    f.write('  console.log("1. Creating incident with a mock medical profile contact (+919876543210)...");\n')
    f.write('  const createRes = await fetch("http://localhost:3000/api/incidents", { method: "POST", headers, body: JSON.stringify({ kind: "CRASH", reason: "Testing Medical Profile Contact Routing", contacts: ["+919876543210"] }) });\n')
    f.write('  const { incident } = await createRes.json();\n')
    f.write('  console.log("2. Incident Created! ID:", incident.id);\n')
    f.write('  console.log("3. Dispatching incident to test Twilio routing...");\n')
    f.write('  const dispatchRes = await fetch("http://localhost:3000/api/incidents/" + incident.id + "/dispatch", { method: "POST", headers });\n')
    f.write('  const data = await dispatchRes.json();\n')
    f.write('  console.log("\\n--- DISPATCH RESULTS ---");\n')
    f.write('  data.incident.deliveries.forEach(d => {\n')
    f.write('    console.log(Channel:  | To:  | Status:  );\n')
    f.write('  });\n')
    f.write('}\n')
    f.write('runTest();\n')
