with open('scripts/smoke-test-dispatch.ts', 'w', encoding='utf-8') as f:
    f.write('import dotenv from "dotenv";\n')
    f.write('import twilio from "twilio";\n')
    f.write('dotenv.config();\n')
    f.write('const client = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN);\n')
    f.write('async function runTest() {\n')
    f.write('  console.log("=== ROAD SOS END-TO-END DISPATCH SMOKE TEST ===");\n')
    f.write('  try {\n')
    f.write('    const fromNumber = process.env.TWILIO_FROM_NUMBER;\n')
    f.write('    const testToNumber = process.env.Hospital_NUMBER || process.env.POLICE_NUMBER;\n')
    f.write('    if (!fromNumber) throw new Error("Missing TWILIO_FROM_NUMBER");\n')
    f.write('    console.log("Attempting to send SMS from " + fromNumber + " to " + testToNumber + "...");\n')
    f.write('    const msg = await client.messages.create({ body: "ROAD SOS SMOKE TEST: This is a diagnostic test of the Twilio dispatch system.", from: fromNumber, to: testToNumber });\n')
    f.write('    console.log("[SUCCESS] SMS queued/sent! SID: " + msg.sid);\n')
    f.write('    console.log("Attempting to initiate Call from " + fromNumber + " to " + testToNumber + "...");\n')
    f.write('    const twiml = new twilio.twiml.VoiceResponse();\n')
    f.write('    twiml.say({ loop: 2 }, "Road S O S Smoke test. This is a diagnostic call. The system is functioning normally. Goodbye.");\n')
    f.write('    const call = await client.calls.create({ to: testToNumber, from: fromNumber, twiml: twiml.toString() });\n')
    f.write('    console.log("[SUCCESS] Call initiated! SID: " + call.sid);\n')
    f.write('  } catch (err: any) { console.error("[FAILED] Twilio dispatch failed:", err.message || err); }\n')
    f.write('}\n')
    f.write('runTest();\n')
